// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time information.
const (
	GitCommit             string = "615ae3a059"
	Version               string = "dev"
	BuildTime             string = "2023-04-27T11:05:06.000000000+00:00"
	IAmStatic             string = "true"
	PlatformName          string = ""
	ProductName           string = ""
	DefaultProductLicense string = ""
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
